version: "3.9"

services:
  fe:
    image: captrivia-fe
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
  be:
    build: .
    ports:
      - "8080:8080"
